"""Initial migration

Revision ID: de4124fb507c
Revises: 
Create Date: 2026-01-16 14:39:01.511089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de4124fb507c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('canned_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_auto_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('faq_auto_response', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tickets',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('marketplace', sa.String(length=50), nullable=False),
    sa.Column('marketplace_conversation_id', sa.String(length=200), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('ticket_status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('conversation_start_date', sa.DateTime(), nullable=False),
    sa.Column('last_updated_date', sa.DateTime(), nullable=False),
    sa.Column('order_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('related_listing_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('marketplace_conversation_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('authored', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('image_attachments', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_tags',
    sa.Column('ticket_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_tags')
    op.drop_table('messages')
    op.drop_table('tickets')
    op.drop_table('tags')
    op.drop_table('faq_auto_responses')
    op.drop_table('canned_responses')
    op.drop_table('agents')
    # ### end Alembic commands ###
